### ISSUE TITLE
LibraOffice Calc 7.2.4: No Add-in button in Tools?

### ISSUE THREAD

**Issue by davidjayjackson** [vondoRishi/AdvanceOfficeChart#5]
I installed the Advance Office Chart add-in, without problems but when I click on the "Tools" menu I don't see option for "Add In"?

TX
David

**Comment by vondoRishi** [comment]
Thank you for reporting this. At present I do not have "LibraOffice Calc 7.2.4" but I have checked this on LibraOffice Calc 6.0.7 and it is also true for that.
However, in my LibraOffice I can see the AdvanceOfficeChart from View -> Toolbars -> "Add on 1".
Please try this and let me know.
It could be in some other place due to major updates by LibraOffice.

**Comment by davidjayjackson** [comment]
Here is a screen shot
![add-in](https://user-images.githubusercontent.com/46544155/146841314-0d1e0b9e-088e-4957-9d2f-95d9fe855579.png)
.
